/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import modelo.Empleado;

/**
 *
 * @author daw1
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        selectorFicheros = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        lDni = new javax.swing.JLabel();
        lNombre = new javax.swing.JLabel();
        lTipo = new javax.swing.JLabel();
        lHoras = new javax.swing.JLabel();
        lIngresos = new javax.swing.JLabel();
        bModificar = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        tfIngresos = new javax.swing.JTextField();
        tfDni = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        cbTipo = new javax.swing.JComboBox<>();
        ftfSalario = new javax.swing.JFormattedTextField();
        lSalario1 = new javax.swing.JLabel();
        sHoras = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bListado = new javax.swing.JButton();
        rbDni = new javax.swing.JRadioButton();
        rbNombre = new javax.swing.JRadioButton();
        rbIngresos = new javax.swing.JRadioButton();
        lOrden = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        miAbrir = new javax.swing.JMenuItem();
        miGuardar = new javax.swing.JMenuItem();
        mEmpleado = new javax.swing.JMenu();
        miNuevo = new javax.swing.JMenuItem();
        miBuscar = new javax.swing.JMenuItem();

        selectorFicheros.setFileFilter(new FileFilter(){
            public boolean accept(File f){
                String n=f.getName();
                boolean b=false;
                if(f.isDirectory() || n.endsWith(".csv"))
                b=true;
                return b;
            }
            public String getDescription(){
                return "Archivos (*.csv)";
            }

        });
        selectorFicheros.setCurrentDirectory(new java.io.File("C:\\Users\\daw1.IS31WX11\\Dropbox\\DATOS\\PROGRAMACION\\Actividades\\2T\\UD05A05\\AppBanco\\src\\main\\java\\es\\sauces\\appbanco"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del empleado"));

        lDni.setText("DNI");

        lNombre.setText("NOMBRE");

        lTipo.setText("TIPO");

        lHoras.setText("HORAS");

        lIngresos.setText("INGRESOS");

        bModificar.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        bModificar.setText("MODIFCAR");

        bBorrar.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        bBorrar.setText("BORRAR");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        tfIngresos.setEditable(false);

        tfDni.setEditable(false);

        tfNombre.setEditable(false);

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIJO", "EVENTUAL" }));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        ftfSalario.setEditable(false);
        ftfSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        lSalario1.setText("SALARIO");

        sHoras.setModel(new javax.swing.SpinnerNumberModel(0, 0, 200, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTipo)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lDni))
                    .addComponent(lHoras)
                    .addComponent(lIngresos)
                    .addComponent(lSalario1))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfDni)
                        .addComponent(tfNombre)
                        .addComponent(cbTipo, 0, 120, Short.MAX_VALUE)
                        .addComponent(ftfSalario)
                        .addComponent(tfIngresos))
                    .addComponent(sHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(bBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(bModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDni))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNombre)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSalario1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lHoras)
                    .addComponent(sHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lIngresos)
                    .addComponent(tfIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(bBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de empleados"));

        etm=new EmpleadoTableModel();
        jTable1.setModel(etm);
        /*jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener);
        public void valueChanged(ListSelectionEvent ev){
            int fila=jTable1.getSelectedRow();
            if(fila>=0){
                mostrarDni(jTable1.getValueAt(fila,0));
                mostrarNombre(jTable1.getValueAt(fila,1));
                mostrarDni(jTable1.getValueAt(fila,2));
                mostrarDni(jTable1.getValueAt(fila,3));
                mostrarDni(jTable1.getValueAt(fila,4));
                mostrarDni(jTable1.getValueAt(fila,5));
            }
        }*/
        jScrollPane1.setViewportView(jTable1);

        bListado.setText("LISTADO DE EMPLEADOS");

        buttonGroup1.add(rbDni);
        rbDni.setText("DNI");

        buttonGroup1.add(rbNombre);
        rbNombre.setText("NOMBRE");

        buttonGroup1.add(rbIngresos);
        rbIngresos.setText("INGRESOS");

        lOrden.setText("ORDEN DEL LISTADO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(271, 271, 271)
                                .addComponent(bListado, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(lOrden)
                                .addGap(93, 93, 93)
                                .addComponent(rbDni)
                                .addGap(75, 75, 75)
                                .addComponent(rbNombre)
                                .addGap(60, 60, 60)
                                .addComponent(rbIngresos)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(bListado)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDni)
                    .addComponent(rbNombre)
                    .addComponent(rbIngresos)
                    .addComponent(lOrden))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mArchivo.setText("Archivo");

        miAbrir.setText("Abrir...");
        miAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAbrirActionPerformed(evt);
            }
        });
        miAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAbrirActionPerformed(evt);
            }
        });
        mArchivo.add(miAbrir);

        miGuardar.setText("Guardar...");
        mArchivo.add(miGuardar);

        jMenuBar1.add(mArchivo);

        mEmpleado.setText("Empleado");

        miNuevo.setText("Nuevo...");
        miNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNuevoActionPerformed(evt);
            }
        });
        mEmpleado.add(miNuevo);

        miBuscar.setText("Buscar...");
        mEmpleado.add(miBuscar);

        jMenuBar1.add(mEmpleado);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 260, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bBorrarActionPerformed

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoActionPerformed

    private void miNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNuevoActionPerformed
       if (this.dialogo.mostrar() == DialogoEmpleado.ACEPTAR) {
            tfDni.setText(dialogo.getDni());
            tfNombre.setText(dialogo.getNombre());
            cbTipo.setSelectedItem(dialogo.getTipo());
            ftfSalario.setValue(dialogo.getSalario());
            sHoras.getComponentCount();
            controlador.crearEmpleado();
        }
    }//GEN-LAST:event_miNuevoActionPerformed

    private void miAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAbrirActionPerformed
        if (selectorFicheros.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            controlador.cargarEmpleados();
        }
    }//GEN-LAST:event_miAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    private Controlador controlador;
    private DialogoEmpleado dialogo = new DialogoEmpleado(this, true);
    
    public void setControlador(Controlador controlador){
        this.controlador = controlador;
    }
    
    public int mostrar() {
        opcion = CANCELAR;
        limpiarCampos();
        this.setVisible(true);
        return opcion;
    }
    
    public void limpiarCampos() {
        tfDni.setText("");
        tfNombre.setText("");
        ftfSalario.setValue(0.0f);        
        cbTipo.setSelectedItem(0); 
        sHoras.setValue(0);
    }
    
    public static final int ACEPTAR = 1;
    public static final int CANCELAR = 0;
    private int opcion;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bListado;
    private javax.swing.JButton bModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JFormattedTextField ftfSalario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private EmpleadoTableModel etm;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lDni;
    private javax.swing.JLabel lHoras;
    private javax.swing.JLabel lIngresos;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lOrden;
    private javax.swing.JLabel lSalario1;
    private javax.swing.JLabel lTipo;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenu mEmpleado;
    private javax.swing.JMenuItem miAbrir;
    private javax.swing.JMenuItem miBuscar;
    private javax.swing.JMenuItem miGuardar;
    private javax.swing.JMenuItem miNuevo;
    private javax.swing.JRadioButton rbDni;
    private javax.swing.JRadioButton rbIngresos;
    private javax.swing.JRadioButton rbNombre;
    private javax.swing.JSpinner sHoras;
    private javax.swing.JFileChooser selectorFicheros;
    private javax.swing.JTextField tfDni;
    private javax.swing.JTextField tfIngresos;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables

    public String getTipo(){
        return cbTipo.getSelectedItem().toString();
    }
    
    public String getDni() {
        return tfDni.getText();
    }
    
    public String getNombre(){
        return tfNombre.getText();
    }
    
    public float getSalario(){
        return (float) ftfSalario.getValue();
    }
    
    public int getHoras(){
        return sHoras.getComponentCount();
    }
    
    public String getArchivo(){
        return selectorFicheros.getSelectedFile().getAbsolutePath();
    }
    
    public String getOrden(){
        return null;
    }
    
    public void mostrarTipo(String tipo){
        cbTipo.setSelectedItem(tipo);
    }
    
    public void mostrarDni(String dni){
        tfDni.setText(dni);
    }
    
    public void mostrarNombre(String nombre){
        tfNombre.setText(nombre);
    }
    
    public void mostrarSalario(float salario){
        ftfSalario.setValue(salario);
    }
    
    public void mostrarHoras(int horas){
        sHoras.setValue(horas);
    }
    
    public void mostrarIngresos(float ingresos){
        tfIngresos.setText(Float.toString(ingresos));
    }
    
    public void listarEmpleados(List<Empleado> listado){
        
    }
        
    public void mostrarMensaje(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    public boolean solicitarConfirmacion(){
        return true;
    }
}
