/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
import java.io.File;
import java.text.DecimalFormatSymbols;
import java.util.List;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileFilter;
import modelo.DniException;
import modelo.Empleado;

/**
 *
 * @author daw1
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        selectorFicheros = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        lDni = new javax.swing.JLabel();
        lNombre = new javax.swing.JLabel();
        lTipo = new javax.swing.JLabel();
        lHoras = new javax.swing.JLabel();
        lIngresos = new javax.swing.JLabel();
        bModificar = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        tfIngresos = new javax.swing.JTextField();
        tfDni = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        cbTipo = new javax.swing.JComboBox<>();
        ftfSalario = new javax.swing.JFormattedTextField();
        lSalario1 = new javax.swing.JLabel();
        sHoras = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bListado = new javax.swing.JButton();
        rbDni = new javax.swing.JRadioButton();
        rbNombre = new javax.swing.JRadioButton();
        rbIngresos = new javax.swing.JRadioButton();
        lOrden = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        miAbrir = new javax.swing.JMenuItem();
        miGuardar = new javax.swing.JMenuItem();
        mEmpleado = new javax.swing.JMenu();
        miNuevo = new javax.swing.JMenuItem();
        miBuscar = new javax.swing.JMenuItem();
        mUsuario = new javax.swing.JMenu();
        miLogin = new javax.swing.JMenuItem();
        miLogout = new javax.swing.JMenuItem();

        selectorFicheros.setCurrentDirectory(new File("."));
        selectorFicheros.addChoosableFileFilter(new FileFilter(){
            public boolean accept(File f){
                String n=f.getName();
                boolean b=false;
                if(f.isDirectory() || n.endsWith(".csv"))
                b=true;
                return b;
            }
            public String getDescription(){
                return "Archivos (*.csv)";
            }
        });
        selectorFicheros.addChoosableFileFilter(new FileFilter(){
            public boolean accept(File f){
                String n=f.getName();
                boolean b=false;
                if(f.isDirectory() || n.endsWith(".json"))
                b=true;
                return b;
            }
            public String getDescription(){
                return "Archivos (*.json)";
            }
        });
        selectorFicheros.addChoosableFileFilter(new FileFilter(){
            public boolean accept(File f){
                String n=f.getName();
                boolean b=false;
                if(f.isDirectory() || n.endsWith(".obj"))
                b=true;
                return b;
            }
            public String getDescription(){
                return "Archivos (*.obj)";
            }
        });
        selectorFicheros.addChoosableFileFilter(new FileFilter(){
            public boolean accept(File f){
                String n=f.getName();
                boolean b=false;
                if(f.isDirectory() || n.endsWith(".xml"))
                b=true;
                return b;
            }
            public String getDescription(){
                return "Archivos (*.xml)";
            }
        });
        selectorFicheros.setCurrentDirectory(new java.io.File("C:\\Users\\daw1.IS31WX11\\Dropbox\\DATOS\\PROGRAMACION\\Actividades\\3T\\appNominas"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del empleado"));

        lDni.setText("DNI");

        lNombre.setText("NOMBRE");

        lTipo.setText("TIPO");

        lHoras.setText("HORAS");
        lHoras.setVisible(false);

        lIngresos.setText("INGRESOS");

        bModificar.setText("MODIFICAR");
        bModificar.setEnabled(false);
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        bBorrar.setText("BORRAR");
        bBorrar.setEnabled(false);
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        tfIngresos.setEditable(false);
        tfIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIngresosActionPerformed(evt);
            }
        });

        tfDni.setEditable(false);

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIJO", "EVENTUAL" }));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
                cambiarTipo(evt);
            }
        });

        ftfSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        lSalario1.setText("SALARIO");

        sHoras.setModel(new javax.swing.SpinnerNumberModel(0, 0, 200, 1));
        sHoras.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTipo)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lDni))
                    .addComponent(lHoras)
                    .addComponent(lIngresos)
                    .addComponent(lSalario1))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfDni)
                        .addComponent(tfNombre)
                        .addComponent(cbTipo, 0, 120, Short.MAX_VALUE)
                        .addComponent(ftfSalario)
                        .addComponent(tfIngresos))
                    .addComponent(sHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(bBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(bModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDni))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNombre)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSalario1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lHoras)
                    .addComponent(sHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lIngresos)
                    .addComponent(tfIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(bBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de empleados"));

        etm=new EmpleadoTableModel();
        jTable1.setModel(etm);
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent lse){
                int fila=jTable1.getSelectedRow();
                if(fila>=0){
                    mostrarDni((String)jTable1.getValueAt(fila,0));
                    mostrarNombre((String)jTable1.getValueAt(fila,1));
                    mostrarTipo((String)jTable1.getValueAt(fila,5));
                    mostrarSalario((float)jTable1.getValueAt(fila,2));
                    mostrarHoras((int)jTable1.getValueAt(fila,3));
                    mostrarIngresos((float)jTable1.getValueAt(fila,4));
                }
            }
        });
        jScrollPane1.setViewportView(jTable1);

        bListado.setText("LISTADO DE EMPLEADOS");
        bListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListadoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbDni);
        rbDni.setSelected(true);
        rbDni.setText("DNI");
        rbDni.setActionCommand("dni");
        rbDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDniActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbNombre);
        rbNombre.setText("NOMBRE");
        rbNombre.setActionCommand("nombre");
        rbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNombreActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbIngresos);
        rbIngresos.setText("INGRESOS");
        rbIngresos.setActionCommand("ingresos");

        lOrden.setText("ORDEN DEL LISTADO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(271, 271, 271)
                                .addComponent(bListado, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(lOrden)
                                .addGap(93, 93, 93)
                                .addComponent(rbDni)
                                .addGap(75, 75, 75)
                                .addComponent(rbNombre)
                                .addGap(60, 60, 60)
                                .addComponent(rbIngresos)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(bListado)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDni)
                    .addComponent(rbNombre)
                    .addComponent(rbIngresos)
                    .addComponent(lOrden))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mArchivo.setText("Archivo");

        miAbrir.setText("Abrir...");
        miAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAbrirActionPerformed(evt);
            }
        });
        mArchivo.add(miAbrir);

        miGuardar.setText("Guardar...");
        miGuardar.setEnabled(false);
        miGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGuardarActionPerformed(evt);
            }
        });
        mArchivo.add(miGuardar);

        jMenuBar1.add(mArchivo);

        mEmpleado.setText("Empleado");

        miNuevo.setText("Nuevo...");
        miNuevo.setEnabled(false);
        miNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNuevoActionPerformed(evt);
            }
        });
        mEmpleado.add(miNuevo);

        miBuscar.setText("Buscar...");
        miBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBuscarActionPerformed(evt);
            }
        });
        mEmpleado.add(miBuscar);

        jMenuBar1.add(mEmpleado);

        mUsuario.setText("Usuario");

        miLogin.setText("Iniciar sesion");
        miLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLoginActionPerformed(evt);
            }
        });
        mUsuario.add(miLogin);

        miLogout.setText("Cerrar sesion");
        miLogout.setEnabled(false);
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        mUsuario.add(miLogout);

        jMenuBar1.add(mUsuario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 260, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        controlador.eliminarEmpleado();
    }//GEN-LAST:event_bBorrarActionPerformed

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoActionPerformed

    private void miNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNuevoActionPerformed
       if (this.dialogo.mostrar() == DialogoEmpleado.ACEPTAR) {
            mostrarDni(dialogo.getDni());
            mostrarNombre(dialogo.getNombre());
            mostrarTipo(dialogo.getTipo());
            mostrarSalario(dialogo.getSalario());
            mostrarHoras(dialogo.getHoras());
           try {
               controlador.crearEmpleado();
           } catch (DniException ex) {
               Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
           }
        }
    }//GEN-LAST:event_miNuevoActionPerformed

    private void miAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAbrirActionPerformed
        if (selectorFicheros.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            controlador.cargarEmpleados();
        }
    }//GEN-LAST:event_miAbrirActionPerformed

    private void cambiarTipo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarTipo
        if(this.cbTipo.getSelectedItem().equals("FIJO")){
            this.lHoras.setVisible(false);
            this.sHoras.setVisible(false);
        }
        else{
            this.lHoras.setVisible(true);
            this.sHoras.setVisible(true);
        }
    }//GEN-LAST:event_cambiarTipo

    private void miBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBuscarActionPerformed
        String dni=JOptionPane.showInputDialog("DNI");
        mostrarDni(dni);
        controlador.buscarEmpleado();
    }//GEN-LAST:event_miBuscarActionPerformed

    private void rbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNombreActionPerformed

    private void miGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGuardarActionPerformed
        if (selectorFicheros.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            controlador.guardarEmpleados();
        }
    }//GEN-LAST:event_miGuardarActionPerformed

    private void rbDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDniActionPerformed

    private void bListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListadoActionPerformed
        controlador.listarEmpleados();
    }//GEN-LAST:event_bListadoActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        if(!tfNombre.getText().isBlank() && !tfDni.getText().isBlank()) {
            controlador.modificarEmpleado();
        }
    }//GEN-LAST:event_bModificarActionPerformed

    private void tfIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIngresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIngresosActionPerformed

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        controlador.hacerLogout();
    }//GEN-LAST:event_miLogoutActionPerformed

    private void miLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLoginActionPerformed
        if(credenciales.mostrar()==Credenciales.ACEPTAR){
            controlador.hacerLogin();
        }
    }//GEN-LAST:event_miLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    private Controlador controlador;
    private DialogoEmpleado dialogo = new DialogoEmpleado(this, true);
    
    public void setControlador(Controlador controlador){
        this.controlador = controlador;
    }
    
    public int mostrar() {
        opcion = CANCELAR;
        limpiarCampos();
        this.setVisible(true);
        return opcion;
    }
    
    public void limpiarCampos() {
        tfDni.setText("");
        tfNombre.setText("");
        ftfSalario.setValue(0.0f);        
        cbTipo.setSelectedItem(0); 
        sHoras.setValue(0);
    }
    
    public static final int ACEPTAR = 1;
    public static final int CANCELAR = 0;
    private int opcion;
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bListado;
    private javax.swing.JButton bModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JFormattedTextField ftfSalario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private EmpleadoTableModel etm;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lDni;
    private javax.swing.JLabel lHoras;
    private javax.swing.JLabel lIngresos;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lOrden;
    private javax.swing.JLabel lSalario1;
    private javax.swing.JLabel lTipo;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenu mEmpleado;
    private javax.swing.JMenu mUsuario;
    private javax.swing.JMenuItem miAbrir;
    private javax.swing.JMenuItem miBuscar;
    private javax.swing.JMenuItem miGuardar;
    private javax.swing.JMenuItem miLogin;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miNuevo;
    private javax.swing.JRadioButton rbDni;
    private javax.swing.JRadioButton rbIngresos;
    private javax.swing.JRadioButton rbNombre;
    private javax.swing.JSpinner sHoras;
    private javax.swing.JFileChooser selectorFicheros;
    private javax.swing.JTextField tfDni;
    private javax.swing.JTextField tfIngresos;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables

    public String getTipo(){
        return cbTipo.getSelectedItem().toString();
    }
    
    public String getDni() {
        return tfDni.getText();
    }
    
    public String getNombre(){
        return tfNombre.getText();
    }
    
    public float getSalario(){
        DecimalFormatSymbols simbolos = new DecimalFormatSymbols();
        simbolos.setDecimalSeparator('.');
        simbolos.setGroupingSeparator(',');
        return ((Number) this.ftfSalario.getValue()).floatValue();
    }
    
    public int getHoras(){
        return (int)sHoras.getValue();
    }
    
    public String getArchivo(){
        return selectorFicheros.getSelectedFile().getAbsolutePath();
    }
    
    public String getOrden(){
        return this.buttonGroup1.getSelection().getActionCommand();
    }
    
    public void mostrarTipo(String tipo){
        cbTipo.setSelectedItem(tipo);
    }
    
    public void mostrarDni(String dni){
        tfDni.setText(dni);
    }
    
    public void mostrarNombre(String nombre){
        tfNombre.setText(nombre);
    }
    
    public void mostrarSalario(float salario){
        ftfSalario.setValue(salario);
    }
    
    public void mostrarHoras(int horas){
        sHoras.setValue(horas);
    }
    
    public void mostrarIngresos(float ingresos){
        tfIngresos.setText(Float.toString(ingresos));
    }
    
    public void listarEmpleados(List<Empleado> listado){
        etm.setListado(listado);
    }
        
    public void mostrarMensaje(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    public boolean solicitarConfirmacion(){
        return true;
    }
    
    
    
    Credenciales credenciales=new Credenciales(this,true); 
            
    public void pedirCredenciales() {
        if(credenciales.mostrar()==Credenciales.ACEPTAR){
            controlador.hacerLogin();
        }
    }

    public String getUsuario() {
        return credenciales.getUsuario();
    }

    public char[] getPassword() {
        return credenciales.getPassword();
    }

    public void cambiarUsuario(String registrado) {
        if(registrado.equals("registrado")){
            this.miGuardar.setEnabled(true);
            this.miNuevo.setEnabled(true);
            this.bBorrar.setEnabled(true);
            this.bModificar.setEnabled(true);
            this.miLogin.setEnabled(false);
            this.miLogout.setEnabled(true);
        }
        else{
            this.miGuardar.setEnabled(false);
            this.miNuevo.setEnabled(false);
            this.bBorrar.setEnabled(false);
            this.bModificar.setEnabled(false);
            this.miLogin.setEnabled(true);
            this.miLogout.setEnabled(false);
        
        }
    }
    
}
